name: Deploy to staging

on:
  push:
    branches: [ "develop", "staging" ]
  pull_request:
    branches: [ "main", "develop" ]

concurrency:
  group: staging
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend image (staging)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/iai-backend:staging
            ${{ secrets.DOCKERHUB_USERNAME }}/iai-backend:${{ github.sha }}

      - name: Build & push web image (staging)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/iai-web:staging
            ${{ secrets.DOCKERHUB_USERNAME }}/iai-web:${{ github.sha }}

  deploy-staging:
    needs: build-and-push-staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ secrets.STAGING_URL }}

    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.29.0"

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_STAGING }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy latest staging images
        run: |
          kubectl set image deployment/iai-backend backend=${{ secrets.DOCKERHUB_USERNAME }}/iai-backend:staging --record
          kubectl set image deployment/iai-web web=${{ secrets.DOCKERHUB_USERNAME }}/iai-web:staging --record

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/iai-backend
          kubectl rollout status deployment/iai-web
